version: 2
jobs:
  build:
    docker:
      - image: tinhnc96/glc-deployer:latest
    steps:
      - checkout
      - run: cp .env.example .env

      # composer cache
      - restore_cache:
          keys:
            - vendor-v1-{{ checksum "composer.lock" }}
      - run:  composer install
      - save_cache:
          key: vendor-v1-{{ checksum "composer.lock" }}
          paths:
            - vendor
  deploy_development:
    docker:
      - image: mattrayner/lamp:latest-1804
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - "74:28:47:90:34:86:12:6d:91:d7:c0:6b:b4:86:8a:98"
      - run:
          name: Install Deployer
          command: |
            curl -LO https://deployer.org/deployer.phar
            mv deployer.phar /usr/local/bin/dep
            chmod +x /usr/local/bin/dep
      - run:
          name: Deploy to develop environment
          command: |
            if [ -z `ssh-keygen -F '52.220.48.43'` ]; then
              ssh-keyscan -H '52.220.48.43' >> ~/.ssh/known_hosts
            fi
            dep deploy development -vv

workflows:
  version: 2
  build_and_deploy_development:
    jobs:
      - build
      - deploy_development:
          requires:
            - build
